#!/bin/bash
cd "$(dirname "$0")"
source ./script/setup.sh

build_version="0.0.0-SNAPSHOT"
codesign_identity="yoke-codesign"
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --codesign-identity) codesign_identity="$2"; shift 2;;
        *) echo "Unknown option $1" > /dev/stderr; exit 1 ;;
    esac
done

#################
### GENERATE  ###
#################

export XCODEGEN_AEROSPACE_CODE_SIGN_IDENTITY="$codesign_identity"
export XCODEGEN_AEROSPACE_VERSION="$build_version"

# Version + git hash
cat > Sources/Common/versionGenerated.swift <<EOF
// FILE IS GENERATED BY build-release-yoke.sh
public let aeroSpaceAppVersion = "$build_version"
EOF

cat > Sources/Common/gitHashGenerated.swift <<EOF
// FILE IS GENERATED BY build-release-yoke.sh
public let gitHash = "$(git rev-parse HEAD)"
public let gitShortHash = "$(git rev-parse --short HEAD)"
EOF

# Regenerate xcodeproj
./script/install-dep.sh --xcodegen
./.deps/xcodegen/xcodegen

#############
### BUILD ###
#############

rm -rf .release && mkdir .release

xcode_configuration="Release"
xcodebuild -version
xcodebuild-pretty .release/xcodebuild.log clean build \
    -scheme AeroSpace \
    -destination "generic/platform=macOS" \
    -configuration "$xcode_configuration" \
    -derivedDataPath .xcode-build

git checkout Sources/Common/versionGenerated.swift Sources/Common/gitHashGenerated.swift

cp -r ".xcode-build/Build/Products/$xcode_configuration/Yoke.app" .release

################
### VALIDATE ###
################

expected_layout=$(cat <<EOF
.release/Yoke.app
.release/Yoke.app/Contents
.release/Yoke.app/Contents/_CodeSignature
.release/Yoke.app/Contents/_CodeSignature/CodeResources
.release/Yoke.app/Contents/MacOS
.release/Yoke.app/Contents/MacOS/Yoke
.release/Yoke.app/Contents/Resources
.release/Yoke.app/Contents/Resources/default-config.toml
.release/Yoke.app/Contents/Resources/AppIcon.icns
.release/Yoke.app/Contents/Resources/Assets.car
.release/Yoke.app/Contents/Info.plist
.release/Yoke.app/Contents/PkgInfo
EOF
)

if test "$expected_layout" != "$(find .release/Yoke.app)"; then
    echo "!!! Expected/Actual layout don't match !!!"
    find .release/Yoke.app
    exit 1
fi

codesign -v .release/Yoke.app

############
### PACK ###
############

cd .release
    mkdir -p "Yoke-v$build_version"
    cp -r Yoke.app "Yoke-v$build_version"
    zip -r "Yoke-v$build_version.zip" "Yoke-v$build_version"
cd -

echo ""
echo "=== Built Yoke-v$build_version.zip ==="
echo "SHA-256: $(shasum -a 256 .release/Yoke-v$build_version.zip | awk '{print $1}')"
