#!/bin/bash
cd "$(dirname "$0")/.."
source ./script/setup.sh

zip_uri=''
build_version="0.0.0-SNAPSHOT"
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --zip-uri) zip_uri="$2"; shift 2;;
        *) echo "Unknown arg $1"; exit 1;;
    esac
done

if test -z "$zip_uri"; then echo "--zip-uri is mandatory" > /dev/stderr; exit 1; fi

zip_file=''
if test -f "$zip_uri"; then
    zip_file=$zip_uri
    zip_uri="file://$(realpath "$zip_file")"
elif grep -q '^http' <<< "$zip_uri"; then
    zip_file=/tmp/Yoke-tmp.zip
    rm -rf $zip_file
    curl -L "$zip_uri" -o $zip_file
else
    echo "$zip_uri doesn't exist" > /dev/stderr; exit 1
fi
sha=$(shasum -a 256 "$zip_file" | awk '{print $1}')

cask_version=':latest'
zip_root_dir="Yoke-v$build_version"
if ! grep -q SNAPSHOT <<< "$build_version"; then
    cask_version="'$build_version'"
    zip_root_dir=$(sed "s/$build_version/#{version}/g" <<< "$zip_root_dir")
    zip_uri=$(sed "s/$build_version/#{version}/g" <<< "$zip_uri")
fi

mkdir -p .release
cat > ".release/yoke.rb" <<EOF
cask "yoke" do # GENERATED BY build-yoke-cask.sh
  version $cask_version
  sha256 "$sha"

  url "$zip_uri"
  name "Yoke"
  desc "Gamepad HUD for tiling window management"
  homepage "https://github.com/ip7e/yoke"

  depends_on macos: ">= :ventura"

  app "$zip_root_dir/Yoke.app"

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/Yoke.app"
  end
end
EOF

echo "Generated .release/yoke.rb"
